### ISSUE TITLE
Migrating ANR to TMPNET [with subtasks]

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#2091]
- [ ] Create TMPNET package/service within CLI https://github.com/ava-labs/avalanche-cli/issues/2509
- [ ] Prototype basic local network implementation using tmpnet https://github.com/ava-labs/avalanche-cli/issues/2510
- [ ] Replace ANR usage with tmpnet for local networks https://github.com/ava-labs/avalanche-cli/issues/2511
- [ ] Replace ANR usage with tmpnet for local clusters https://github.com/ava-labs/avalanche-cli/issues/2579

**Comment by meaghanfitzgerald** [comment]
@marun Tooling will schedule time with you to discuss if tmpnet supports all use cases currently fulfilled by ANR

**Comment by felipemadero** [comment]
@meaghanfitzgerald some points/questions:

- I don't believe we need to have both implementations working at the same time (--tmpnet flag): which is the criteria for that? with direct replacement we can directly use the local network and local cluster e2e CI stuff which has pretty good coverage. also, having two options living together is going to complicate the flow implementations. we can just have the branch for that and do the merge into main when it is good enough.
- local cluster implementation is missing in the migration steps:  also uses ANR
- IMO the two main sub issues should be: (1) replace local networks (also having a tmpnet CLI package as a deliberable), (2) replace local clusters (using that deliverable)

**Comment by felipemadero** [comment]
Closed by https://github.com/ava-labs/avalanche-cli/pull/2680
